store:
  name: s3://sentinel-cogs
  prefixes:
    - sentinel-s2-l2a-cogs/10/C
  obstore_config:
    skip_signature: True
    region: us-west-2
concurrency:
  n_consumers: 1000
  list_chunk_size: 10000
  max_buffer_size: 1000000
  write_chunk_size: 100000